# Generated by Django 4.1.7 on 2023-05-16 21:57

import datetime
from django.conf import settings
import django.contrib.auth.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnoLetivo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('anoletivo', models.CharField(default='2022/2023', max_length=9)),
                ('ativo', models.BooleanField(default=True)),
                ('datainicio', models.DateField()),
                ('datafinal', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Departamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(default='Departamento de Engenharia informática', max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='DSD',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Periodo', models.CharField(default='2022/2023', max_length=9)),
                ('codDisci', models.IntegerField()),
                ('disciplina', models.CharField(default='2022/2023', max_length=9)),
                ('instituic', models.CharField(default='2022/2023', max_length=9)),
                ('instituto', models.CharField(default='2022/2023', max_length=9)),
                ('departamento', models.CharField(default='2022/2023', max_length=9)),
                ('turma', models.CharField(default='2022/2023', max_length=9)),
                ('codCurso', models.CharField(max_length=9)),
                ('curso', models.CharField(default='2022/2023', max_length=9)),
                ('codDocente', models.CharField(max_length=9)),
                ('docente', models.CharField(default='2022/2023', max_length=9)),
                ('funcDocente', models.CharField(default='2022/2023', max_length=9)),
                ('instDocente', models.CharField(default='2022/2023', max_length=9)),
                ('departDocente', models.CharField(default='2022/2023', max_length=9)),
                ('horasSem', models.CharField(max_length=9)),
                ('horasPeri', models.CharField(max_length=9)),
                ('factor', models.CharField(default='2022/2023', max_length=9)),
                ('horasServ', models.CharField(max_length=9)),
                ('Datainicial', models.CharField(max_length=9)),
                ('DataFim', models.CharField(max_length=9)),
                ('Nome', models.CharField(default='2022/2023', max_length=9)),
                ('Agrupamento', models.CharField(default='2022/2023', max_length=9)),
            ],
        ),
        migrations.CreateModel(
            name='Edificio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(default='Default name', max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='EstatisticaPedido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Status', models.CharField(default='Em Análise', max_length=255)),
                ('NmrPedido', models.IntegerField(default=1)),
                ('TempoMedio', models.CharField(default='1 dia', max_length=255)),
                ('VarTempo', models.CharField(default='3 dias', max_length=255)),
                ('percetagem', models.CharField(default='40%', max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Faculdade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(default='FCT - Faculdade de Ciencias e Tecnologia', max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Pedido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(default='nossa', max_length=255)),
                ('assunto', models.CharField(default='assunto', max_length=255)),
                ('desc', models.CharField(default='Default description', max_length=1200)),
                ('dia', models.DateField()),
                ('status', models.CharField(default='Em Análise', max_length=255)),
                ('atribuido', models.CharField(default='Não Atribuido', max_length=255)),
                ('diaCriado', models.DateField(default=datetime.date.today)),
            ],
        ),
        migrations.CreateModel(
            name='Sala',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('NomeInstituição', models.CharField(default='Default name', max_length=255)),
                ('DescEdifício', models.CharField(default='Default name', max_length=255)),
                ('DescSala', models.CharField(default='Default name', max_length=255)),
                ('DesCategoria', models.CharField(default='Default name', max_length=255)),
                ('IdTipoSala', models.CharField(default='Default name', max_length=255)),
                ('LotaçãoPresencialSala', models.CharField(default='Default name', max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='UnidadesCurriculares',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('AnoLetivo', models.CharField(max_length=255)),
                ('Regência', models.CharField(max_length=255)),
                ('Docentes', models.CharField(default='Zézinha', max_length=255)),
                ('Tipo', models.CharField(default='Null', max_length=200)),
                ('Horas', models.CharField(default='00h', max_length=255)),
                ('Curso', models.CharField(max_length=255)),
                ('Código', models.IntegerField(default=1)),
                ('Descriçao', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Utilizador',
            fields=[
                ('user_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('telefone', models.IntegerField()),
                ('valido', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'Utilizador',
            },
            bases=('auth.user',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Administrador',
            fields=[
                ('utilizador_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='main.utilizador')),
                ('gabinete', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'Administrador',
            },
            bases=('main.utilizador',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Docente',
            fields=[
                ('utilizador_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='main.utilizador')),
                ('gabinete', models.CharField(db_column='Gabinete', max_length=255)),
                ('departamento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.departamento')),
                ('faculdade', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.faculdade')),
            ],
            options={
                'db_table': 'Docente',
            },
            bases=('main.utilizador',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Funcionario',
            fields=[
                ('utilizador_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='main.utilizador')),
            ],
            options={
                'db_table': 'Funcionário',
            },
            bases=('main.utilizador',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='PedidoUC',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uc', models.CharField(default='LES', max_length=255)),
                ('descri', models.CharField(default='Default description', max_length=1200)),
                ('tipo', models.CharField(default='Unidades Curriculares', max_length=255)),
                ('tarefa', models.CharField(default='Criar', max_length=255)),
                ('regente', models.CharField(default='Default description', max_length=1200)),
                ('pedido', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.pedido')),
            ],
        ),
        migrations.CreateModel(
            name='PedidosOutros',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('arquivo', models.FileField(blank=True, null=True, upload_to='')),
                ('pedido', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.pedido')),
            ],
        ),
        migrations.CreateModel(
            name='PedidoSala',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('edi', models.CharField(default='Default name', max_length=255)),
                ('sal', models.CharField(default='Default name', max_length=255)),
                ('uc', models.CharField(default='LES', max_length=255)),
                ('hora_de_inicio', models.TimeField()),
                ('status', models.CharField(default='Em Análise', max_length=255)),
                ('hora_de_fim', models.TimeField()),
                ('descri', models.CharField(default='Default description', max_length=1200)),
                ('dia', models.DateField(default=datetime.date.today)),
                ('tarefa', models.CharField(default='Criar', max_length=255)),
                ('pedido', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.pedido')),
            ],
        ),
        migrations.CreateModel(
            name='PedidoHorario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uc', models.CharField(default='LES', max_length=255)),
                ('hora_inicio', models.TimeField()),
                ('hora_fim', models.TimeField()),
                ('descri', models.CharField(default='Default description', max_length=1200)),
                ('tarefa', models.CharField(default='Criar', max_length=255)),
                ('dia', models.DateField(default=datetime.date.today)),
                ('pedido', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.pedido')),
            ],
        ),
        migrations.CreateModel(
            name='Outros',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('desc_pedido', models.CharField(max_length=255)),
                ('pedido_unidades_curriculares_id', models.IntegerField()),
                ('pedidos_outros_id', models.IntegerField()),
                ('pedidos_outros_pedido_id', models.IntegerField()),
                ('pedidos_outros_pedido_funcionario_id', models.IntegerField()),
                ('pedidos_outros_pedido_docente_id', models.IntegerField()),
            ],
            options={
                'unique_together': {('id', 'pedido_unidades_curriculares_id', 'pedidos_outros_id', 'pedidos_outros_pedido_id', 'pedidos_outros_pedido_funcionario_id', 'pedidos_outros_pedido_docente_id')},
            },
        ),
        migrations.CreateModel(
            name='Horario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField()),
                ('tipo', models.IntegerField()),
                ('pedido_unidades_curriculares_id', models.IntegerField()),
                ('pedido_horario_id', models.IntegerField()),
                ('pedido_horario_pedido_id', models.IntegerField()),
                ('pedido_horario_pedido_funcionario_id', models.IntegerField()),
                ('pedido_horario_pedido_docente_id', models.IntegerField()),
            ],
            options={
                'unique_together': {('id', 'pedido_unidades_curriculares_id', 'pedido_horario_id', 'pedido_horario_pedido_id', 'pedido_horario_pedido_funcionario_id', 'pedido_horario_pedido_docente_id')},
            },
        ),
        migrations.AddField(
            model_name='pedido',
            name='Docente',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.docente'),
        ),
        migrations.AddField(
            model_name='pedido',
            name='Funcionario',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.funcionario'),
        ),
    ]
