# Generated by Django 4.1.7 on 2023-05-16 18:14

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='diaCriado',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
