# Generated by Django 4.1.7 on 2023-05-20 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_pedido_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='Rejeitarpedido',
            field=models.CharField(default='Nao sei', max_length=1000),
        ),
    ]
