# Generated by Django 4.1.7 on 2023-03-19 21:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_docente_funcionario_delete_docent'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pedido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_pedido', models.IntegerField()),
                ('criacao', models.DateField()),
                ('estado_pedido', models.IntegerField()),
                ('docente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.docente')),
                ('funcionario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.funcionario')),
            ],
            options={
                'unique_together': {('id', 'funcionario', 'docente')},
            },
        ),
        migrations.CreateModel(
            name='PedidoUC',
            fields=[
                ('id', models.PositiveIntegerField(primary_key=True, serialize=False)),
                ('unidades_curriculares_id', models.PositiveIntegerField()),
                ('pedido_id', models.PositiveIntegerField()),
                ('pedido_funcionario_id', models.PositiveIntegerField()),
                ('pedido_docente_id', models.PositiveIntegerField()),
                ('dia', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='UnidadesCurriculares',
            fields=[
                ('ID', models.IntegerField(auto_created=True, primary_key=True, serialize=False)),
                ('AnoLetivo', models.CharField(max_length=255)),
                ('NomeDaUC', models.CharField(max_length=255)),
                ('Regência', models.CharField(max_length=255)),
                ('ECTs', models.IntegerField()),
                ('Curso', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Sala',
            fields=[
                ('ID', models.IntegerField(primary_key=True, serialize=False)),
                ('Edificio', models.CharField(max_length=255)),
                ('TipoSala', models.IntegerField()),
                ('Capacidade', models.IntegerField()),
                ('PedidoSalaID', models.IntegerField()),
                ('NumeroSala', models.FloatField()),
                ('PedidoSalaPedidoID', models.IntegerField()),
                ('PedidoSalaPedidoUnidades_CurricularesID', models.IntegerField()),
                ('PedidoSalaPedidoFuncionárioID', models.IntegerField()),
                ('PedidoSalaPedidoDocenteID', models.IntegerField()),
            ],
            options={
                'unique_together': {('ID', 'PedidoSalaID', 'PedidoSalaPedidoID', 'PedidoSalaPedidoUnidades_CurricularesID', 'PedidoSalaPedidoFuncionárioID', 'PedidoSalaPedidoDocenteID')},
            },
        ),
        migrations.CreateModel(
            name='Outros',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('desc_pedido', models.CharField(max_length=255)),
                ('pedido_unidades_curriculares_id', models.IntegerField()),
                ('pedidos_outros_id', models.IntegerField()),
                ('pedidos_outros_pedido_id', models.IntegerField()),
                ('pedidos_outros_pedido_funcionario_id', models.IntegerField()),
                ('pedidos_outros_pedido_docente_id', models.IntegerField()),
            ],
            options={
                'unique_together': {('id', 'pedido_unidades_curriculares_id', 'pedidos_outros_id', 'pedidos_outros_pedido_id', 'pedidos_outros_pedido_funcionario_id', 'pedidos_outros_pedido_docente_id')},
            },
        ),
        migrations.CreateModel(
            name='Horario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField()),
                ('tipo', models.IntegerField()),
                ('pedido_unidades_curriculares_id', models.IntegerField()),
                ('pedido_horario_id', models.IntegerField()),
                ('pedido_horario_pedido_id', models.IntegerField()),
                ('pedido_horario_pedido_funcionario_id', models.IntegerField()),
                ('pedido_horario_pedido_docente_id', models.IntegerField()),
            ],
            options={
                'unique_together': {('id', 'pedido_unidades_curriculares_id', 'pedido_horario_id', 'pedido_horario_pedido_id', 'pedido_horario_pedido_funcionario_id', 'pedido_horario_pedido_docente_id')},
            },
        ),
        migrations.CreateModel(
            name='PedidosOutros',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pedido_funcionario_id', models.IntegerField()),
                ('pedido_docente_id', models.IntegerField()),
                ('descricao', models.CharField(max_length=255)),
                ('dia', models.DateField()),
                ('pedido', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.pedido')),
            ],
            options={
                'unique_together': {('id', 'pedido', 'pedido_funcionario_id', 'pedido_docente_id')},
            },
        ),
        migrations.CreateModel(
            name='PedidoSala',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pedido_unidades_curriculares_id', models.IntegerField()),
                ('pedido_funcionario_id', models.IntegerField()),
                ('pedido_docente_id', models.IntegerField()),
                ('hora_de_inicio', models.DateField()),
                ('hora_de_fim', models.DateField()),
                ('dia', models.DateField()),
                ('pedido', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.pedido')),
            ],
            options={
                'unique_together': {('id', 'pedido', 'pedido_unidades_curriculares_id', 'pedido_funcionario_id', 'pedido_docente_id')},
            },
        ),
        migrations.CreateModel(
            name='PedidoHorario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pedido_unidades_curriculares_id', models.IntegerField()),
                ('pedido_funcionario_id', models.IntegerField()),
                ('pedido_docente_id', models.IntegerField()),
                ('dia', models.DateField()),
                ('hora_inicio', models.DateField()),
                ('hora_fim', models.DateField()),
                ('pedido', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.pedido')),
            ],
            options={
                'unique_together': {('id', 'pedido', 'pedido_funcionario_id', 'pedido_docente_id')},
            },
        ),
    ]
