# Generated by Django 4.1.7 on 2023-05-16 18:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_pedido_diacriado'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='Docente',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.docente'),
        ),
    ]
