# Generated by Django 4.1.7 on 2023-05-20 18:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_pedido_rejeitarpedido'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='Anoletivo',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.anoletivo'),
        ),
    ]
