# Generated by Django 4.1.7 on 2023-05-16 23:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_pedido_docente'),
    ]

    operations = [
        migrations.AlterField(
            model_name='docente',
            name='departamento',
            field=models.CharField(db_column='Departamento', max_length=255),
        ),
        migrations.AlterField(
            model_name='docente',
            name='faculdade',
            field=models.CharField(db_column='Faculdade', max_length=255),
        ),
    ]
