# Generated by Django 4.1.7 on 2023-03-23 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_pedido_pedidouc_unidadescurriculares_sala_outros_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='pedidohorario',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='pedidohorario',
            name='desc',
            field=models.CharField(default='Default description', max_length=1200),
        ),
        migrations.AddField(
            model_name='pedidohorario',
            name='uc',
            field=models.CharField(default='max', max_length=255),
        ),
        migrations.RemoveField(
            model_name='pedidohorario',
            name='pedido',
        ),
        migrations.RemoveField(
            model_name='pedidohorario',
            name='pedido_docente_id',
        ),
        migrations.RemoveField(
            model_name='pedidohorario',
            name='pedido_funcionario_id',
        ),
        migrations.RemoveField(
            model_name='pedidohorario',
            name='pedido_unidades_curriculares_id',
        ),
    ]
