# Generated by Django 4.1.7 on 2023-03-23 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_alter_pedidohorario_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedidohorario',
            name='hora_fim',
            field=models.TimeField(),
        ),
        migrations.AlterField(
            model_name='pedidohorario',
            name='hora_inicio',
            field=models.TimeField(),
        ),
    ]
