# Generated by Django 4.1.7 on 2023-05-20 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_pedido_anoletivo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='anoletivo',
            name='ativo',
            field=models.BooleanField(default=False),
        ),
    ]
