# Generated by Django 4.1.7 on 2023-03-23 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_alter_pedidohorario_hora_fim_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedidohorario',
            name='uc',
            field=models.CharField(default='LES', max_length=255),
        ),
    ]
