# Generated by Django 4.1.7 on 2023-05-20 23:45

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_alter_anoletivo_ativo'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='diaFinal',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
