# Generated by Django 4.1.7 on 2023-03-25 00:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_alter_pedidohorario_uc'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='pedidosoutros',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='pedidosoutros',
            name='assunto',
            field=models.CharField(default='none', max_length=255),
        ),
        migrations.AlterField(
            model_name='pedidosoutros',
            name='descricao',
            field=models.CharField(max_length=1200),
        ),
        migrations.AlterField(
            model_name='pedidosoutros',
            name='dia',
            field=models.DateField(default=0),
        ),
        migrations.RemoveField(
            model_name='pedidosoutros',
            name='pedido',
        ),
        migrations.RemoveField(
            model_name='pedidosoutros',
            name='pedido_docente_id',
        ),
        migrations.RemoveField(
            model_name='pedidosoutros',
            name='pedido_funcionario_id',
        ),
    ]
