# Generated by Django 4.1.7 on 2023-05-21 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_alter_dsd_agrupamento_alter_dsd_datafim_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Turma',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codDisci', models.IntegerField()),
                ('disciplina', models.CharField(default='2022/2023', max_length=255)),
            ],
        ),
    ]
