# Generated by Django 4.1.7 on 2023-05-21 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_pedido_diafinal'),
    ]

    operations = [
        migrations.AddField(
            model_name='docente',
            name='ativo',
            field=models.BooleanField(db_column='ativo', default=True),
        ),
        migrations.AddField(
            model_name='docente',
            name='codigo_docente',
            field=models.IntegerField(db_column='codigo_codigo_docente', default=1),
        ),
        migrations.AddField(
            model_name='docente',
            name='nome',
            field=models.CharField(db_column='Nome', default='ze', max_length=255),
        ),
    ]
