# Generated by Django 4.1.7 on 2023-05-21 17:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_docente_ativo_docente_codigo_docente_docente_nome'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='docente',
            name='ativo',
        ),
        migrations.RemoveField(
            model_name='docente',
            name='codigo_docente',
        ),
        migrations.RemoveField(
            model_name='docente',
            name='nome',
        ),
    ]
