# Generated by Django 4.1.7 on 2023-05-21 17:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_turma'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Turma',
        ),
        migrations.RemoveField(
            model_name='dsd',
            name='Agrupamento',
        ),
        migrations.RemoveField(
            model_name='dsd',
            name='Nome',
        ),
        migrations.RemoveField(
            model_name='dsd',
            name='codCurso',
        ),
        migrations.RemoveField(
            model_name='dsd',
            name='departamento',
        ),
        migrations.RemoveField(
            model_name='dsd',
            name='factor',
        ),
        migrations.RemoveField(
            model_name='dsd',
            name='funcDocente',
        ),
        migrations.RemoveField(
            model_name='dsd',
            name='horasPeri',
        ),
        migrations.RemoveField(
            model_name='dsd',
            name='horasServ',
        ),
        migrations.RemoveField(
            model_name='dsd',
            name='instDocente',
        ),
        migrations.RemoveField(
            model_name='dsd',
            name='instituic',
        ),
    ]
