# Generated by Django 4.1.7 on 2023-03-25 00:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_alter_pedidosoutros_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedidosoutros',
            name='dia',
            field=models.DateField(),
        ),
    ]
