# Generated by Django 4.1.7 on 2023-03-25 01:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_alter_pedidosoutros_dia'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PedidosOutros',
        ),
    ]
