# Generated by Django 4.1.7 on 2023-05-21 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_docente_ativo_docente_codigo_docente_docente_nome'),
    ]

    operations = [
        migrations.CreateModel(
            name='Docente_import',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(db_column='Gabinete', max_length=255)),
                ('nome', models.CharField(db_column='Faculdade', max_length=255)),
                ('ativo', models.CharField(db_column='Departamento', max_length=255)),
            ],
        ),
        migrations.RemoveField(
            model_name='docente',
            name='ativo',
        ),
        migrations.RemoveField(
            model_name='docente',
            name='codigo_docente',
        ),
        migrations.RemoveField(
            model_name='docente',
            name='nome',
        ),
    ]
