# Generated by Django 4.1.7 on 2023-05-21 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_docente_import_remove_docente_ativo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='docente_import',
            name='ativo',
            field=models.BooleanField(db_column='ativo', default=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='docente_import',
            name='codigo',
            field=models.CharField(db_column='codigo', max_length=255),
        ),
        migrations.AlterField(
            model_name='docente_import',
            name='nome',
            field=models.CharField(db_column='nome', max_length=255),
        ),
    ]
