# Generated by Django 4.1.7 on 2023-03-27 22:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_pedidosoutros'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pedidouc',
            name='pedido_docente_id',
        ),
        migrations.RemoveField(
            model_name='pedidouc',
            name='pedido_funcionario_id',
        ),
        migrations.RemoveField(
            model_name='pedidouc',
            name='pedido_id',
        ),
        migrations.RemoveField(
            model_name='pedidouc',
            name='unidades_curriculares_id',
        ),
        migrations.AddField(
            model_name='pedidouc',
            name='assunto',
            field=models.CharField(default='assunto', max_length=255),
        ),
        migrations.AddField(
            model_name='pedidouc',
            name='desc',
            field=models.CharField(default='Default description', max_length=1200),
        ),
        migrations.AddField(
            model_name='pedidouc',
            name='uc',
            field=models.CharField(default='LES', max_length=255),
        ),
        migrations.AlterField(
            model_name='pedidouc',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
