# Generated by Django 4.1.7 on 2023-03-27 23:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_remove_pedidouc_pedido_docente_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedidohorario',
            name='assunto',
            field=models.CharField(default='assunto', max_length=255),
        ),
    ]
