# Generated by Django 4.1.7 on 2023-05-21 17:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_rename_dsd_turma'),
        ('main', '0011_alter_docente_import_ativo_and_more'),
    ]

    operations = [
    ]
