# Generated by Django 4.1.7 on 2023-03-28 00:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_pedidohorario_assunto'),
    ]

    operations = [
        migrations.CreateModel(
            name='Edificio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(default='Default name', max_length=255)),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='pedidosala',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='sala',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='pedidosala',
            name='desc',
            field=models.CharField(default='Default description', max_length=1200),
        ),
        migrations.AddField(
            model_name='pedidosala',
            name='sala',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='main.sala'),
        ),
        migrations.AlterField(
            model_name='sala',
            name='TipoSala',
            field=models.CharField(max_length=255),
        ),
        migrations.RemoveField(
            model_name='pedidosala',
            name='pedido',
        ),
        migrations.RemoveField(
            model_name='pedidosala',
            name='pedido_docente_id',
        ),
        migrations.RemoveField(
            model_name='pedidosala',
            name='pedido_funcionario_id',
        ),
        migrations.RemoveField(
            model_name='pedidosala',
            name='pedido_unidades_curriculares_id',
        ),
        migrations.RemoveField(
            model_name='sala',
            name='ID',
        ),
        migrations.RemoveField(
            model_name='sala',
            name='PedidoSalaID',
        ),
        migrations.RemoveField(
            model_name='sala',
            name='PedidoSalaPedidoDocenteID',
        ),
        migrations.RemoveField(
            model_name='sala',
            name='PedidoSalaPedidoFuncionárioID',
        ),
        migrations.RemoveField(
            model_name='sala',
            name='PedidoSalaPedidoID',
        ),
        migrations.RemoveField(
            model_name='sala',
            name='PedidoSalaPedidoUnidades_CurricularesID',
        ),
        migrations.AddField(
            model_name='pedidosala',
            name='edificio',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='main.edificio'),
        ),
        migrations.AlterField(
            model_name='sala',
            name='Edificio',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.edificio'),
        ),
        migrations.AddField(
            model_name='sala',
            name='id',
            field=models.IntegerField(default=1, primary_key=True, serialize=False),
        ),
    ]
