# Generated by Django 4.1.7 on 2023-03-28 00:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_edificio_alter_pedidosala_unique_together_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pedidosala',
            name='edificio',
        ),
        migrations.AddField(
            model_name='pedidosala',
            name='Edificio',
            field=models.CharField(default='Default name', max_length=255),
        ),
    ]
