# Generated by Django 4.1.7 on 2023-03-28 00:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0014_remove_pedidosala_edificio_pedidosala_edificio'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pedidosala',
            old_name='Edificio',
            new_name='edificio',
        ),
        migrations.AlterField(
            model_name='pedidosala',
            name='hora_de_fim',
            field=models.TimeField(),
        ),
        migrations.AlterField(
            model_name='pedidosala',
            name='hora_de_inicio',
            field=models.TimeField(),
        ),
        migrations.AlterField(
            model_name='pedidosala',
            name='sala',
            field=models.CharField(default='Default name', max_length=255),
        ),
    ]
