# Generated by Django 4.1.7 on 2023-04-11 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0016_rename_edificio_pedidosala_edi_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedidosoutros',
            name='tipo',
            field=models.CharField(default='Outros', max_length=255),
        ),
    ]
