# Generated by Django 4.1.7 on 2023-04-11 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0017_pedidosoutros_tipo'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedidohorario',
            name='tipo',
            field=models.CharField(default='Horário', max_length=255),
        ),
        migrations.AddField(
            model_name='pedidosala',
            name='assunto',
            field=models.CharField(default='assunto', max_length=255),
        ),
        migrations.AddField(
            model_name='pedidosala',
            name='tipo',
            field=models.CharField(default='Sala', max_length=255),
        ),
        migrations.AddField(
            model_name='pedidouc',
            name='tipo',
            field=models.CharField(default='Unidades Curriculares', max_length=255),
        ),
    ]
