# Generated by Django 4.1.7 on 2023-04-13 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0018_pedidohorario_tipo_pedidosala_assunto_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pedido',
            old_name='criacao',
            new_name='dia',
        ),
        migrations.AlterUniqueTogether(
            name='pedido',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='pedido',
            name='assunto',
            field=models.CharField(default='assunto', max_length=255),
        ),
        migrations.AddField(
            model_name='pedido',
            name='desc',
            field=models.CharField(default='Default description', max_length=1200),
        ),
        migrations.RemoveField(
            model_name='pedido',
            name='estado_pedido',
        ),
    ]
