# Generated by Django 4.1.7 on 2023-04-13 14:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0019_rename_criacao_pedido_dia_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pedido',
            name='docente',
        ),
        migrations.RemoveField(
            model_name='pedido',
            name='funcionario',
        ),
        migrations.RemoveField(
            model_name='pedido',
            name='tipo_pedido',
        ),
    ]
