# Generated by Django 4.1.7 on 2023-04-13 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0020_remove_pedido_docente_remove_pedido_funcionario_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pedidouc',
            old_name='desc',
            new_name='descri',
        ),
        migrations.RemoveField(
            model_name='pedidouc',
            name='assunto',
        ),
        migrations.RemoveField(
            model_name='pedidouc',
            name='dia',
        ),
        migrations.AddField(
            model_name='pedidouc',
            name='tarefa',
            field=models.CharField(default='Criar', max_length=255),
        ),
    ]
