# Generated by Django 4.1.7 on 2023-04-13 14:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0021_rename_desc_pedidouc_descri_remove_pedidouc_assunto_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedidouc',
            name='pedido',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='main.pedido'),
        ),
    ]
