# Generated by Django 4.1.7 on 2023-04-26 17:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0022_pedidouc_pedido'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pedidohorario',
            old_name='desc',
            new_name='descri',
        ),
        migrations.RemoveField(
            model_name='pedidohorario',
            name='assunto',
        ),
        migrations.RemoveField(
            model_name='pedidohorario',
            name='dia',
        ),
        migrations.AddField(
            model_name='pedidohorario',
            name='pedido',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='main.pedido'),
        ),
    ]
