# Generated by Django 4.1.7 on 2023-04-27 00:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0023_rename_desc_pedidohorario_descri_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pedidohorario',
            name='tipo',
        ),
        migrations.AlterField(
            model_name='pedidohorario',
            name='pedido',
            field=models.ForeignKey(default=87, on_delete=django.db.models.deletion.CASCADE, to='main.pedido'),
        ),
        migrations.AlterField(
            model_name='pedidouc',
            name='pedido',
            field=models.ForeignKey(default=87, on_delete=django.db.models.deletion.CASCADE, to='main.pedido'),
        ),
    ]
