# Generated by Django 4.1.7 on 2023-04-27 00:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0024_remove_pedidohorario_tipo_alter_pedidohorario_pedido_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pedidouc',
            name='pedido',
        ),
        migrations.RemoveField(
            model_name='pedidouc',
            name='tipo',
        ),
        migrations.AddField(
            model_name='pedido',
            name='tipo',
            field=models.CharField(default='nossa', max_length=255),
        ),
        migrations.AlterField(
            model_name='pedidohorario',
            name='pedido',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.pedido'),
        ),
    ]
