# Generated by Django 4.1.7 on 2023-04-27 00:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0025_remove_pedidouc_pedido_remove_pedidouc_tipo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedidohorario',
            name='status',
            field=models.CharField(default='Em Análise', max_length=255),
        ),
    ]
