# Generated by Django 4.1.7 on 2023-04-27 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0026_pedidohorario_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pedidohorario',
            name='status',
        ),
        migrations.AddField(
            model_name='pedido',
            name='status',
            field=models.CharField(default='Em Análise', max_length=255),
        ),
    ]
