# Generated by Django 4.1.7 on 2023-04-27 18:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0028_pedidohorario_tarefa'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='Funcionario',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='main.funcionario'),
        ),
        migrations.AddField(
            model_name='pedido',
            name='atribuido',
            field=models.CharField(default='Não Atribuido', max_length=255),
        ),
    ]
