# Generated by Django 4.1.7 on 2023-04-27 20:52

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0029_pedido_funcionario_pedido_atribuido'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedidohorario',
            name='dia',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
