# Generated by Django 4.1.7 on 2023-05-08 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0030_pedidohorario_dia'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='unidadescurriculares',
            name='ID',
        ),
        migrations.AddField(
            model_name='unidadescurriculares',
            name='Docentes',
            field=models.CharField(default='Zézinha', max_length=255),
        ),
        migrations.AddField(
            model_name='unidadescurriculares',
            name='Horas',
            field=models.CharField(default='00h', max_length=255),
        ),
        migrations.AddField(
            model_name='unidadescurriculares',
            name='Tipo',
            field=models.CharField(default='Null', max_length=200),
        ),
        migrations.AddField(
            model_name='unidadescurriculares',
            name='id',
            field=models.BigAutoField(auto_created=True, default=1, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
    ]
