# Generated by Django 4.1.7 on 2023-05-08 18:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0031_remove_unidadescurriculares_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='unidadescurriculares',
            name='ECTs',
        ),
    ]
