# Generated by Django 4.1.7 on 2023-05-08 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0032_remove_unidadescurriculares_ects'),
    ]

    operations = [
        migrations.AlterField(
            model_name='unidadescurriculares',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
