# Generated by Django 4.1.7 on 2023-05-08 18:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0033_alter_unidadescurriculares_id'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UnidadesCurriculares',
        ),
    ]
