# Generated by Django 4.1.7 on 2023-05-08 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0034_delete_unidadescurriculares'),
    ]

    operations = [
        migrations.CreateModel(
            name='UnidadesCurriculares',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('AnoLetivo', models.CharField(max_length=255)),
                ('NomeDaUC', models.CharField(max_length=255)),
                ('Regência', models.CharField(max_length=255)),
                ('Docentes', models.CharField(default='Zézinha', max_length=255)),
                ('Tipo', models.CharField(default='Null', max_length=200)),
                ('Horas', models.CharField(default='00h', max_length=255)),
                ('Curso', models.CharField(max_length=255)),
            ],
        ),
    ]
