# Generated by Django 4.1.7 on 2023-05-08 18:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0035_unidadescurriculares'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='unidadescurriculares',
            name='NomeDaUC',
        ),
    ]
