# Generated by Django 4.1.7 on 2023-05-08 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0036_remove_unidadescurriculares_nomedauc'),
    ]

    operations = [
        migrations.AddField(
            model_name='unidadescurriculares',
            name='Código',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='unidadescurriculares',
            name='Descriçao',
            field=models.CharField(default='Ensino da Vida', max_length=255),
            preserve_default=False,
        ),
    ]
