# Generated by Django 4.1.7 on 2023-05-08 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0037_unidadescurriculares_código_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='unidadescurriculares',
            name='Código',
            field=models.IntegerField(default=1),
        ),
    ]
