# Generated by Django 4.1.7 on 2023-05-09 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0038_alter_unidadescurriculares_código'),
    ]

    operations = [
        migrations.CreateModel(
            name='EstatisticaPedido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Status', models.CharField(default='Em Análise', max_length=255)),
                ('NmrPedido', models.IntegerField(default=1)),
                ('TempoMedio', models.CharField(default='1 dia', max_length=255)),
                ('VarTempo', models.CharField(default='3 dias', max_length=255)),
            ],
        ),
    ]
