# Generated by Django 4.1.7 on 2023-05-09 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0039_estatisticapedido'),
    ]

    operations = [
        migrations.AddField(
            model_name='estatisticapedido',
            name='percetagem',
            field=models.CharField(default='40%', max_length=255),
        ),
    ]
