# Generated by Django 4.2.1 on 2023-05-13 13:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0040_estatisticapedido_percetagem'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnoLetivo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('anoletivo', models.CharField(default='2022/2023', max_length=9)),
                ('ativo', models.BooleanField(default=True)),
                ('datainicio', models.DateField()),
                ('datafinal', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='DSD',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Periodo', models.CharField(default='2022/2023', max_length=9)),
                ('codDisci', models.IntegerField()),
                ('disciplina', models.CharField(default='2022/2023', max_length=9)),
                ('instituic', models.CharField(default='2022/2023', max_length=9)),
                ('instituto', models.CharField(default='2022/2023', max_length=9)),
                ('departamento', models.CharField(default='2022/2023', max_length=9)),
                ('turma', models.CharField(default='2022/2023', max_length=9)),
                ('codCurso', models.CharField(max_length=9)),
                ('curso', models.CharField(default='2022/2023', max_length=9)),
                ('codDocente', models.CharField(max_length=9)),
                ('docente', models.CharField(default='2022/2023', max_length=9)),
                ('funcDocente', models.CharField(default='2022/2023', max_length=9)),
                ('instDocente', models.CharField(default='2022/2023', max_length=9)),
                ('departDocente', models.CharField(default='2022/2023', max_length=9)),
                ('horasSem', models.CharField(max_length=9)),
                ('horasPeri', models.CharField(max_length=9)),
                ('factor', models.CharField(default='2022/2023', max_length=9)),
                ('horasServ', models.CharField(max_length=9)),
                ('Datainicial', models.CharField(max_length=9)),
                ('DataFim', models.CharField(max_length=9)),
                ('Nome', models.CharField(default='2022/2023', max_length=9)),
                ('Agrupamento', models.CharField(default='2022/2023', max_length=9)),
            ],
        ),
        migrations.AddField(
            model_name='pedidouc',
            name='pedido',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='main.pedido'),
        ),
        migrations.AddField(
            model_name='pedidouc',
            name='regente',
            field=models.CharField(default='Default description', max_length=1200),
        ),
        migrations.AddField(
            model_name='pedidouc',
            name='tipo',
            field=models.CharField(default='Unidades Curriculares', max_length=255),
        ),
    ]
