# Generated by Django 4.1.7 on 2023-05-14 03:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0041_anoletivo_dsd_pedidouc_pedido_pedidouc_regente_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='docente',
            old_name='email',
            new_name='arquivo',
        ),
        migrations.RenameField(
            model_name='docente',
            old_name='telefone',
            new_name='codigo',
        ),
        migrations.AddField(
            model_name='docente',
            name='data_emissao_identificacao',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='docente',
            name='data_nascimento',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='docente',
            name='data_validade_identificacao',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='docente',
            name='digito_verificacao',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='docente',
            name='docente',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='docente',
            name='identificacao',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='docente',
            name='individuo',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='docente',
            name='nacionalidade',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='docente',
            name='nbsp',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='docente',
            name='nif',
            field=models.CharField(default=1, max_length=9),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='docente',
            name='pais_fiscal',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='docente',
            name='sexo',
            field=models.CharField(default=1, max_length=2),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='docente',
            name='tipo_identificacao',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='docente',
            name='ativo',
            field=models.CharField(max_length=2),
        ),
    ]
