# Generated by Django 4.1.7 on 2023-05-14 04:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0042_rename_email_docente_arquivo_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pedidosoutros',
            name='assunto',
        ),
        migrations.RemoveField(
            model_name='pedidosoutros',
            name='descricao',
        ),
        migrations.RemoveField(
            model_name='pedidosoutros',
            name='dia',
        ),
        migrations.RemoveField(
            model_name='pedidosoutros',
            name='tipo',
        ),
        migrations.AddField(
            model_name='pedidosoutros',
            name='arquivo',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='pedidosoutros',
            name='pedido',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.pedido'),
        ),
    ]
