# Generated by Django 4.1.7 on 2023-05-15 00:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0044_rename_desc_pedidosala_descri_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sala',
            name='Capacidade',
        ),
        migrations.RemoveField(
            model_name='sala',
            name='Edificio',
        ),
        migrations.RemoveField(
            model_name='sala',
            name='NumeroSala',
        ),
        migrations.RemoveField(
            model_name='sala',
            name='TipoSala',
        ),
        migrations.AddField(
            model_name='sala',
            name='DesCategoria',
            field=models.CharField(default='Default name', max_length=255),
        ),
        migrations.AddField(
            model_name='sala',
            name='DescEdifício',
            field=models.CharField(default='Default name', max_length=255),
        ),
        migrations.AddField(
            model_name='sala',
            name='DescSala',
            field=models.CharField(default='Default name', max_length=255),
        ),
        migrations.AddField(
            model_name='sala',
            name='IdTipoSala',
            field=models.CharField(default='Default name', max_length=255),
        ),
        migrations.AddField(
            model_name='sala',
            name='LotaçãoPresencialSala',
            field=models.CharField(default='Default name', max_length=255),
        ),
        migrations.AddField(
            model_name='sala',
            name='NomeInstituição',
            field=models.CharField(default='Default name', max_length=255),
        ),
        migrations.AlterField(
            model_name='sala',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
