# Generated by Django 4.1.7 on 2023-05-15 13:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0044_alter_pedido_funcionario'),
        ('main', '0045_remove_sala_capacidade_remove_sala_edificio_and_more'),
    ]

    operations = [
    ]
