# Generated by Django 4.1.7 on 2023-05-15 22:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('main', '0052_alter_docente_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='funcionario',
            name='groups',
            field=models.ManyToManyField(blank=True, help_text='The groups this user belongs to.', related_name='funcionario_group_set', related_query_name='funcionario_group', to='auth.group', verbose_name='groups'),
        ),
        migrations.AddField(
            model_name='funcionario',
            name='is_superuser',
            field=models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status'),
        ),
        migrations.AddField(
            model_name='funcionario',
            name='last_login',
            field=models.DateTimeField(blank=True, null=True, verbose_name='last login'),
        ),
        migrations.AddField(
            model_name='funcionario',
            name='password',
            field=models.CharField(default='', max_length=128, verbose_name='password'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='funcionario',
            name='user_permissions',
            field=models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='funcionario_permission_set', related_query_name='funcionario_permission', to='auth.permission', verbose_name='user permissions'),
        ),
        migrations.AlterField(
            model_name='funcionario',
            name='email',
            field=models.CharField(default='gnomo', max_length=255, unique=True),
        ),
    ]
