# Generated by Django 4.1.7 on 2023-05-15 23:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0053_funcionario_groups_funcionario_is_superuser_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='funcionario',
            name='username',
            field=models.CharField(default='gnomo', max_length=255),
        ),
        migrations.AlterField(
            model_name='funcionario',
            name='ativo',
            field=models.BooleanField(default=True),
        ),
    ]
