# Generated by Django 4.1.7 on 2023-05-16 00:27

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0053_funcionario_groups_funcionario_is_superuser_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedidosala',
            name='dia',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AlterField(
            model_name='funcionario',
            name='ativo',
            field=models.BooleanField(default=True),
        ),
    ]
