# Generated by Django 4.1.7 on 2023-05-15 23:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('main', '0054_funcionario_username_alter_funcionario_ativo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Administrador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(default='gnomo', max_length=255)),
                ('first_name', models.CharField(default='gnomo', max_length=255)),
                ('last_name', models.CharField(default='gnomo', max_length=255)),
                ('email', models.CharField(default='gnomo', max_length=255, unique=True)),
                ('telefone', models.IntegerField()),
                ('ativo', models.BooleanField(default=True)),
                ('gabinete', models.CharField(default='C1.54', max_length=255)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to.', related_name='administrador_group_set', related_query_name='administrador_group', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='administrador_permission_set', related_query_name='administrador_permission', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
