# Generated by Django 4.1.7 on 2023-05-15 23:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('main', '0056_departamento_faculdade'),
    ]

    operations = [
        migrations.AddField(
            model_name='docente',
            name='groups',
            field=models.ManyToManyField(blank=True, help_text='The groups this user belongs to.', related_name='docente_group_set', related_query_name='docente_group', to='auth.group', verbose_name='groups'),
        ),
        migrations.AddField(
            model_name='docente',
            name='is_superuser',
            field=models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status'),
        ),
        migrations.AddField(
            model_name='docente',
            name='last_login',
            field=models.DateTimeField(blank=True, null=True, verbose_name='last login'),
        ),
        migrations.AddField(
            model_name='docente',
            name='password',
            field=models.CharField(default='', max_length=128, verbose_name='password'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='docente',
            name='user_permissions',
            field=models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='docente_permission_set', related_query_name='docente_permission', to='auth.permission', verbose_name='user permissions'),
        ),
        migrations.AddField(
            model_name='docente',
            name='username',
            field=models.CharField(default='gnomo', max_length=255),
        ),
        migrations.AlterField(
            model_name='docente',
            name='ativo',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='docente',
            name='departamento',
            field=models.CharField(default='Engenharia', max_length=255),
        ),
        migrations.AlterField(
            model_name='docente',
            name='email',
            field=models.CharField(default='gnomo', max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='docente',
            name='faculdade',
            field=models.CharField(default='FCT', max_length=255),
        ),
        migrations.AlterField(
            model_name='docente',
            name='gabinete',
            field=models.CharField(default='C1.2', max_length=255),
        ),
    ]
